name: build-syllabus
on: [push]
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: apt install python3-sphinx sphinxcontrib-spelling
      - run: cd src ; make
